########################################
# Docker build
########################################
#time sudo docker build -t naisy/jetson-jp461-donkeycar -f Dockerfile.jetson-jp461-donkeycar .
#time sudo docker build -t parkinglotnerds/jetson-jp461-donkeycar -f Dockerfile.jetson-jp461-donkeycar .
#time sudo docker build -t parkinglotnerds/jetson-jp462-donkeycar -f Dockerfile.jetson-jp462-donkeycar .
########################################
# Storage setting
########################################
#sudo service docker stop
#cd /var/run
#sudo mv docker /mnt/ssd250
#sudo ln -s /mnt/ssd250 docker
#sudo service docker start

# https://github.com/NVIDIA/nvidia-docker/issues/1033
# cmake fails unable to find cuda library while building an image
#vi /etc/docker/daemon.json
#{
#    "runtimes": {
#        "nvidia": {
#            "path": "/usr/bin/nvidia-container-runtime",
#            "runtimeArgs": []
#        }
#    },
#    "default-runtime": "nvidia"
#}
#
#service docker stop
#service docker start


# end of information


########################################
# Base OS repogitory
########################################
ARG BASE_IMAGE=naisy/jetson-jp461-deepstream601-triton-base
FROM ${BASE_IMAGE}

ARG USERNAME=jetson
ARG OPENBLAS_CORETYPE=ARMV8
ARG VENV=python3


########################################
# pip package
########################################
USER $USERNAME
RUN . /virtualenv/$VENV/bin/activate \
    && pip install pyfiglet \
    && pip install prettytable \
    && pip install pytest \
    && pip install pytorch_lightning

RUN . /virtualenv/$VENV/bin/activate \
    && cd ~/github \
    && git clone -b main https://github.com/autorope/donkeycar \
    && cd donkeycar \
    && pip install -e .[nano]

RUN . /virtualenv/$VENV/bin/activate \
    && cd ~/github \
    && git clone https://github.com/tawnkramer/gym-donkeycar \
    && cd gym-donkeycar \
    && sed -i 's/python_requires=">=3\.7"/python_requires=">=3.6"/g' setup.py \
    && pip install -e .

RUN . /virtualenv/$VENV/bin/activate \
    && pip install -U pip testresources setuptools \
    && pip install -U futures==3.1.1 protobuf==3.12.2 pybind11==2.5.0 \
    && pip install -U cython==0.29.21 pyserial \
    && pip install -U future==0.18.2 mock==4.0.2 h5py==2.10.0 keras_preprocessing==1.1.2 keras_applications==1.0.8 gast==0.3.3 \
    && pip install -U absl-py==0.9.0 py-cpuinfo==7.0.0 psutil==5.7.2 portpicker==1.3.1 six requests==2.24.0 astor==0.8.1 termcolor==1.1.0 wrapt==1.12.1 google-pasta==0.2.0 \
    && pip install -U gdown


# fix dependancy for *donkey ui*
RUN sudo apt-get update && sudo apt-get install xclip

# install pytorch
#RUN . /virtualenv/$VENV/bin/activate \
#    && wget https://nvidia.box.com/shared/static/p57jwntv436lfrd78inwl7iml6p13fzh.whl \
#    && cp p57jwntv436lfrd78inwl7iml6p13fzh.whl torch-1.8.0-cp36-cp36m-linux_aarch64.whl \
#    && pip install torch-1.8.0-cp36-cp36m-linux_aarch64.whl \
#    && sudo apt-get install -y libjpeg-dev zlib1g-dev libpython3-dev libavcodec-dev libavformat-dev libswscale-dev \
#    && mkdir -p ~/github; cd ~/github \
#    && git clone -b v0.9.0 https://github.com/pytorch/vision torchvision \
#    && cd torchvision \
#    && python setup.py install \
#    && cd ../

RUN sudo sed -i 's/docker-/docker-donkeycar-/g' /root/.bashrc \
    && sed -i 's/docker-/docker-donkeycar-/g' /home/$USERNAME/.bashrc


CMD . /virtualenv/python3/bin/activate && exec bash -c "jupyter-lab --ip=0.0.0.0 --no-browser --ServerApp.root_dir=/ --LabApp.default_url=/lab?file-browser-path=$HOME/data/Notebooks"
